import Link from 'next/link';
import { articles,categories,products } from '@/data/site';
export default function Home(){return <main>
<section className="hero"><div className="container heroGrid"><div><span className="eyebrow">MVP Template • ข้อมูลตัวอย่าง</span><h1>ของชิ้นไหน<br/><em>คุ้มจริง</em> เราช่วยคัดให้</h1><p>เว็บไซต์นี้อยู่ระหว่างพัฒนา เนื้อหาและรายการสินค้าปัจจุบันเป็นข้อมูลตัวอย่างสำหรับตรวจสอบโครงสร้างเท่านั้น</p><div className="heroActions"><Link className="primary" href="#latest">ดูบทความตัวอย่าง</Link><Link className="secondary" href="#categories">เลือกตามหมวด</Link></div><div className="trust"><span>✓ ยังไม่เชื่อมข้อมูลสินค้าจริง</span><span>✓ ยังไม่มีลิงก์ Affiliate จริง</span></div></div><div className="heroCard"><div className="miniLabel">ตัวอย่างโครงสร้างบทความ</div><div className="heroEmoji">🎒</div><h3>ชุดอุปกรณ์ออกทริปสำหรับครอบครัว</h3><p>เนื้อหาตัวอย่างสำหรับทดสอบหน้าเว็บไซต์</p><Link href="/article/family-camping-tent">อ่านตัวอย่าง →</Link></div></div></section>
<section id="categories" className="section container"><div className="sectionHead"><div><span className="eyebrow">เลือกสิ่งที่สนใจ</span><h2>หมวดหมู่หลัก</h2></div><p>เริ่มจากเรื่องที่เราใช้งานและมีประสบการณ์จริง ก่อนขยายไปยังหมวดใหม่</p></div><div className="categoryGrid">{categories.map(c=><Link key={c.slug} className="categoryCard" href={`/category/${c.slug}`}><span>{c.icon}</span><h3>{c.name}</h3><p>{c.description}</p><b>ดูบทความ →</b></Link>)}</div></section>
<section id="latest" className="section soft"><div className="container"><div className="sectionHead"><div><span className="eyebrow">อ่านก่อนซื้อ</span><h2>บทความแนะนำ</h2></div></div><div className="articleGrid">{articles.map(a=><article key={a.slug} className="articleCard"><div className="articleVisual">{a.image}<span>{a.badge}</span></div><div className="articleBody"><small>{categories.find(c=>c.slug===a.category)?.name} · {a.readTime}</small><h3>{a.title}</h3><p>{a.excerpt}</p><Link href={`/article/${a.slug}`}>อ่านบทความ →</Link></div></article>)}</div></div></section>
<section className="section container"><div className="sectionHead"><div><span className="eyebrow">ข้อมูลตัวอย่าง</span><h2>ตัวอย่าง Product Comparison</h2></div><p className="disclaimer">รายการ คะแนน และราคาในส่วนนี้เป็น placeholder สำหรับทดสอบ layout ยังไม่ใช่ข้อมูลสินค้าจริงหรือคำแนะนำให้ซื้อ</p></div><div className="productList">{products.map((p,i)=><div className="productRow" key={p.name}><div className="rank">0{i+1}</div><div><small>{p.category}</small><h3>{p.name}</h3><p>{p.reason}</p></div><div className="score"><b>{p.score}</b><span>/10</span></div><div className="price"><small>ราคาตัวอย่าง</small><b>{p.price}</b></div><span className="shopBtn disabledAction" aria-disabled="true">ยังไม่เชื่อมสินค้า</span></div>)}</div></section>
<section className="container newsletter"><div><span className="eyebrow">ฟังก์ชันที่วางแผนไว้</span><h2>ระบบรับข่าวสารยังไม่เปิดใช้งาน</h2><p>ส่วนนี้เป็นตัวอย่าง layout และยังไม่มีการรับหรือจัดเก็บอีเมล</p></div><div className="newsletterSignup"><input aria-label="อีเมล" placeholder="อีเมลของคุณ" disabled/><button type="button" disabled>ยังไม่เปิดใช้งาน</button></div></section>
</main>}
