import Link from 'next/link';
import { articles,categories,products } from '@/data/site';
export default function Home(){return <main>
<section className="hero"><div className="container heroGrid"><div><span className="eyebrow">รีวิวจริง • เปรียบเทียบง่าย • เลือกได้มั่นใจ</span><h1>ของชิ้นไหน<br/><em>คุ้มจริง</em> เราช่วยคัดให้</h1><p>รวมคู่มือและรีวิวสินค้าจาก Shopee สำหรับคนที่อยากซื้อให้ตรงงาน ไม่เสียเงินฟรี และไม่ต้องเปิดสิบแท็บเพื่อเปรียบเทียบเอง</p><div className="heroActions"><Link className="primary" href="#latest">ดูบทความแนะนำ</Link><Link className="secondary" href="#categories">เลือกตามหมวด</Link></div><div className="trust"><span>✓ เน้นข้อมูลใช้งานจริง</span><span>✓ บอกทั้งข้อดีและข้อจำกัด</span></div></div><div className="heroCard"><div className="miniLabel">ตัวเลือกประจำสัปดาห์</div><div className="heroEmoji">🎒</div><h3>ชุดอุปกรณ์ออกทริปสำหรับครอบครัว</h3><p>รวมของจำเป็นที่ควรมี โดยไม่ซื้อเกินความจำเป็น</p><Link href="/article/family-camping-tent">อ่านคู่มือ →</Link></div></div></section>
<section id="categories" className="section container"><div className="sectionHead"><div><span className="eyebrow">เลือกสิ่งที่สนใจ</span><h2>หมวดหมู่หลัก</h2></div><p>เริ่มจากเรื่องที่เราใช้งานและมีประสบการณ์จริง ก่อนขยายไปยังหมวดใหม่</p></div><div className="categoryGrid">{categories.map(c=><Link key={c.slug} className="categoryCard" href={`/category/${c.slug}`}><span>{c.icon}</span><h3>{c.name}</h3><p>{c.description}</p><b>ดูบทความ →</b></Link>)}</div></section>
<section id="latest" className="section soft"><div className="container"><div className="sectionHead"><div><span className="eyebrow">อ่านก่อนซื้อ</span><h2>บทความแนะนำ</h2></div></div><div className="articleGrid">{articles.map(a=><article key={a.slug} className="articleCard"><div className="articleVisual">{a.image}<span>{a.badge}</span></div><div className="articleBody"><small>{categories.find(c=>c.slug===a.category)?.name} · {a.readTime}</small><h3>{a.title}</h3><p>{a.excerpt}</p><Link href={`/article/${a.slug}`}>อ่านบทความ →</Link></div></article>)}</div></div></section>
<section className="section container"><div className="sectionHead"><div><span className="eyebrow">คัดมาให้แล้ว</span><h2>ตัวเลือกที่น่าสนใจ</h2></div><p className="disclaimer">ราคาตัวอย่างอาจเปลี่ยนแปลง กรุณาตรวจสอบราคาล่าสุดใน Shopee</p></div><div className="productList">{products.map((p,i)=><div className="productRow" key={p.name}><div className="rank">0{i+1}</div><div><small>{p.category}</small><h3>{p.name}</h3><p>{p.reason}</p></div><div className="score"><b>{p.score}</b><span>/10</span></div><div className="price"><small>ราคาโดยประมาณ</small><b>{p.price}</b></div><a className="shopBtn" href={p.url}>ดูใน Shopee</a></div>)}</div></section>
<section className="container newsletter"><div><span className="eyebrow">ไม่พลาดบทความใหม่</span><h2>รับสรุปของน่าใช้เดือนละ 2 ครั้ง</h2><p>ไม่มีสแปม มีเฉพาะคู่มือและสินค้าที่น่าสนใจจริง</p></div><form><input aria-label="อีเมล" placeholder="อีเมลของคุณ"/><button>สมัครรับข่าวสาร</button></form></section>
</main>}
